### ISSUE TITLE
Fake safe odds description unclear

### ISSUE THREAD

**Issue by FalcoGer** [GABRlEL/payday2.pw-Mods#2]
What do the Safe mods do? The description is unclear to me. What does it mean to be "missing blue" for example?

**Comment by GABRlEL** [comment]
Hello there, sorry for the late response - I hope you're still reading this.
I just came back to modding.
The safe mods are for the old safes you can open for skins. Nowadays the skins just seem to drop themselves but back then you had to unbox them.
I hope this is clear to you.

**Comment by GABRlEL** [comment]
Hey, sorry if this was unclear.
If you open a safe, you see a lot of weapons fly by.
![image](https://user-images.githubusercontent.com/26207711/164511028-9b207dcd-4077-4825-8b4d-7cadf61d1837.png)
Think of all the weapons you see here, you get none of them but they hype you up, because you might miss good items.
These items you miss, are manipulated by the mods. Only blues, only purples etc. fly by. Display Real Safe Odds manipulate the odds to reflect the real drop rates from PAYDAY. The faked odds are a bit better than the actual drop odds.
Is this clear enough?

**Comment by FalcoGer** [comment]
So basically the lottery shows you only good prizes but it has already decided what it wants to give you before you see the "roll", and everything is just super cool stuff that is just shown to make you play more. So the whole thing is just cosmetic and your mod makes it be more akin to the real odds of winning stuff (but doesn't actually change anything but the visuals).
Is that it?

**Comment by GABRlEL** [comment]
Exactly, you explained this way better than I ever could.
